### ISSUE TITLE
Switch to BEM For CSS Class Names?

### ISSUE THREAD

**Issue by mlaursen** [mlaursen/react-md#128]
http://getbem.com/naming/

This might simplify some of the existing CSS and reduce some of the code output?

Currently the text field container's css is defined as:

```scss
.md-text-field-container {
  @include md-theme-placeholders($md-secondary-text-color);
  display: inline-block;
  vertical-align: top;

  &.block {
    align-items: center;
    display: flex;

    &.multi-line {
      align-items: flex-start;
      flex-wrap: wrap;
      justify-content: flex-end;

      // scss-lint:disable NestingDepth
      .md-text-field-message {
        width: 100%;
      }
    }

    .md-text-field-label {
      flex-grow: 1;
    }

    .md-text-field-message {
      flex-shrink: 0;
    }
  }

  &.with-message {
    width: $md-text-field-info-width;

    .md-text-field {
      width: 100%;
    }
  }

  &.full-width {
    width: 100%;
  }

  &.disabled {
    @extend %md-disabled-text;
    @include md-theme-placeholders($md-disabled-color);
  }

  // scss-lint:disable VendorPrefix, PseudoElement
  :-moz-placeholder {
    opacity: 1;
  }

  ::-moz-placeholder {
    opacity: 1;
  }

  :-ms-input-placeholder {
    opacity: 1;
  }

  ::-webkit-input-placeholder {
    opacity: 1;
  }
}

```

With BEM, this could be re-written as:

```scss
.md-text-field-container {
  display: inline-block;
  vertical-align: top;

  // scss-lint:disable VendorPrefix, PseudoElement
  :-moz-placeholder {
    opacity: 1;
  }

  ::-moz-placeholder {
    opacity: 1;
  }

  :-ms-input-placeholder {
    opacity: 1;
  }

  ::-webkit-input-placeholder {
    opacity: 1;
  }
}

.md-text-field-container--default {
  @include md-theme-placeholders($md-secondary-text-color);
}

.md-text-field-container--disabled {
  @extend %md-disabled-text;
  @include md-theme-placeholders($md-disabled-color);
}

.flex {
  display: flex;
}

.flex--align-center {
  align-items: center;
}

.flex--align-start {
  align-items: flex-start;
}

.flex--justify-end {
  justify-content: flex-end;
}

.flex--wrap {
  flex-wrap: wrap;
}

.flex--grow {
  flex-grow: 1;
}

.flex--no-shrink {
  flex-shrink: 0;
}

.md-text-field-container--block {
  align-items: center;
  display: flex;
}

.md-text-field-container--with-message {
  width: $md-text-field-info-width;
}

.full-width {
  width: 100%;
}
```

Changing to BEM would require a lot more javascript state checking for which `className`s to apply and there would end up being a lot more CSS classes applied to elements.

It really might just be that I need to clean up the CSS a bit more and look at a more global/reusable scale of existing classes. BEM might help enforce some of those changes for me.
