### ISSUE TITLE
[Dialog] - Unable to scroll large dialog content

### ISSUE THREAD

**Issue by MichalWadowski** [mlaursen/react-md#431]
If height of Dialog content exceed of some height, then part of this content is placed out of Dialog component. I think, if content doesn't fit Dialog, then scroll should be shown.
Add a custom div-container with ```{height 100%; overflow: hidden;}``` doesn't work.
I'm not sure it is react-md, material design or my knowledge lack.

Here is an example: https://codepen.io/MichalWadowski/pen/WOJvRd

**Comment by gniquil** [comment]
Here's my work around. See if this works for you:

After include everything in the scss, put in the following snippet:

```scss

.md-dialog--scrollable {
  .md-dialog {
    display: flex;
    flex-direction: column;

    .md-title--dialog {
      flex-shrink: 0;
      border-bottom: solid 1px get-color('divider', true);
    }
    .md-dialog-content {
      flex-grow: 1;
    }
    .md-dialog-footer {
      flex-shrink: 0;
      border-top: solid 1px get-color('divider', true);
    }
  }
}

```

Then add `md-dialog--scrollable` to the `Dialog` component.
