### ISSUE TITLE
[Grid] - Support a "container" for the grid system

### ISSUE THREAD

**Issue by mikeni** [mlaursen/react-md#472]
Looking at the front page  of the showcase in the docs, 
https://react-md.mlaursen.com/discover-more/showcases

it seems to use materialize
https://bredariol.be/

and in 
https://bredariol.be/product?
it is using react-md

I'm looking to do a fixed with container layout like the front page, is that possible out of the box with react-md?

if not, what are you guys using to achieve that?  My app is  primarily targeting desktop.

**Comment by fkhadra** [comment]
Hey @mikeni,

I'm migrating the old code base written in Phpto react-md. It will be released this month. 

The home page for the new version:
![screenshot from 2017-08-08 11-16-21](https://user-images.githubusercontent.com/5574267/29065122-650f9c04-7c2b-11e7-80ca-389f236b19c4.png)

What do you mean by fixed with container?

**Comment by mikeni** [comment]
there is a max width for container at certain responsive widths, kinda like the picture you posted, you see how the 3 columns are part of a container that has a max width?

basically fixed layout

**Comment by fkhadra** [comment]
Indeed. I created a simple container class for that:

```css
.container {
    width: 100%;
    max-width: 1200px;
    margin: 0 auto;
    padding: 0 20px;
    box-sizing: border-box;
}

@media (min-width: 400px) {
    .container {
        width: 85%;
        padding: 0;
    }
}

@media (min-width: 550px) {
    .container {
        width: 80%;
    }
}
```

I usually do the following:

```javascript
<div className="md-grid container">
// your component here
</div>
```

**Comment by mikeni** [comment]
ah ok, I'm wondering why material frameworks usually don't have this, most are mobile focused.  Material-ui, react-md, etc don't have it, but older frameworks like semantic-ui and bootstrap do

**Comment by fkhadra** [comment]
I don't know too. 
@mlaursen what do you think if react-md had something like 
```css
.md-grid--centered{
    width: 100%;
    max-width: 1200px;
    margin: 0 auto;
    padding: 0 20px;
    box-sizing: border-box;
}

@media (min-width: 400px) {
    .md-grid--centered{
        width: 85%;
        padding: 0;
    }
}

@media (min-width: 550px) {
    .md-grid--centered{
        width: 80%;
    }
}
```

md-grid--centered will act as a modifier for md-grid.
```javascript
<div className="md-grid md-grid--centered">
//component
</div>
```

Just an idea.
