### ISSUE TITLE
[DataTable] - Fixed Table Headers don't display correctly in Mobile Safari

### ISSUE THREAD

**Issue by mlaursen** [mlaursen/react-md#614]
### Description
Mobile safari is great. It is the only browser that will not render the `position: absolute` column headers when `overflow-x: overflow-y: auto` is set. 

### Link to a gist or code sample where the issue can be reproduced
To get around this issue, I created 2 components to get around this issue only for iOS.

```jsx
import React, { PureComponent } from 'react';
import PropTypes from 'prop-types';
import {
  AccessibleFakeButton,
  Portal,
  IconSeparator,
  ResizeObserver,
} from 'react-md';
import getCollapserStyles from 'react-md/lib/utils/getCollapserStyles';

/**
 * Mobile safari's rendering engine is stupid. Period. It is the only rendering engine that hides
 * vertical overflow when `overflow-x: hidden; overflow-y: auto` is applied. To get around this,
 * we have to portal the label out of the main table and then display it with fixed styles.
 *
 * This class applies these fixes and basically is a duplicate of the inner workings of the TableColumn
 * component for applying the sort icon.
 */
export default class MobileSafariHack extends PureComponent {
  static propTypes = {
    id: PropTypes.string.isRequired,
    onClick: PropTypes.func.isRequired,
    sorted: PropTypes.bool,
    sortIcon: PropTypes.node,
    sortIconBefore: PropTypes.bool,
    children: PropTypes.node,
  };

  state = { style: null }

  handleResize = ({ el }) => {
    const { left } = el.getBoundingClientRect();
    const { style } = this.state;
    if (!style || style.left !== left) {
      this.setState({ style: { left } });
    }
  };

  render() {
    const { style } = this.state;
    const { id, sorted, sortIcon, sortIconBefore, onClick, children } = this.props;

    let icon = <span />;
    if (typeof sorted !== 'undefined') {
      icon = React.cloneElement(sortIcon, { className: getCollapserStyles({ flipped: !sorted }) });
    }

    return (
      <span>
        <ResizeObserver
          onResize={this.handleResize}
          target={`[aria-labelledby="${id}"]`}
          watchWidth
        />
        <Portal key="portal" visible>
          <AccessibleFakeButton
            id={id}
            className="stupid-mobile-safari-table-hack md-text--secondary md-text-uppercase"
            onClick={onClick}
            style={style}
            component={IconSeparator}
            label={children}
            iconBefore={sortIconBefore}
          >
            {icon}
          </AccessibleFakeButton>
        </Portal>
      </span>
    );
  }
}
```

```jsx
import React from 'react';
import PropTypes from 'prop-types';
import { FormattedMessage } from 'react-intl';
import { TableColumn } from 'react-md';

import { isIOS } from 'utils/devices';

import MobileSafariHack from './MobileSafariHack';

const Column = ({ id, messageId, rendered, onClick, ...props }) => {
  if (!rendered) {
    return null;
  }

  let content = <span><FormattedMessage id={messageId} /></span>;
  let labelledBy = null;
  let onColumnClick = onClick;
  if (isIOS()) {
    const { sorted, sortIcon, sortIconBefore } = props;
    labelledBy = id;
    onColumnClick = null;

    content = (
      <MobileSafariHack
        id={id}
        onClick={onClick}
        sorted={sorted}
        sortIcon={sortIcon}
        sortIconBefore={sortIconBefore}
      >
        {content}
      </MobileSafariHack>
    );
  }

  return (
    <TableColumn
      {...props}
      aria-labelledby={labelledBy}
      onClick={onColumnClick}
    >
      {content}
    </TableColumn>
  );
};

Column.propTypes = {
  id: PropTypes.string.isRequired,
  messageId: PropTypes.string.isRequired,
  rendered: PropTypes.bool,
  onClick: PropTypes.func,
  grow: PropTypes.bool,
  adjusted: PropTypes.bool,
  sorted: PropTypes.bool,
  sortIcon: PropTypes.node,
  sortIconBefore: PropTypes.bool,
};

Column.defaultProps = {
  adjusted: false,
  rendered: true,
};

export default Column;
```

```scss
.stupid-mobile-safari-table-hack {
  // have to duplicate styles here since it is portal'd out
  align-items: center;
  display: flex;
  font-size: $md-data-table-header-font-size;
  font-weight: $md-font-bold;
  position: fixed;
  top: $md-toolbar-height;
  z-index: $fixed-column-z-index + 1;

  @media #{$md-tablet-landscape-media} {
    top: $md-toolbar-prominent-height;
  }

  &.stupid-mobile-safari-table-hack {
    // react-root styles apply 100% which is what happens when you use a portal. So have to re-enforce the height
    height: $md-data-table-header-height;
  }
}
```

### Version
- React - *.*
- React-MD - 1.2.*
- Browser - Mobile Safari (any -- iPad, iPhone, etc)
